### ISSUE TITLE
Heigth of comboBox

### ISSUE THREAD

**Issue by dagginio** [UN-GCPDS/qt-material#54]
Hello, 
first of all I want to thank you for this nice piece of work. 

I have the following problem. If have different widgets next to each other, and the combo box is slightly bigger (heigher) as the other once (See screenshot). If I remove the corresponding line for the hight of the combo box in the css.template, the combo box gets the same height as widget next to it. However, I saw, that many widgets have a dedicated height properties, so I guess there is reason for this ...

![image](https://user-images.githubusercontent.com/83673789/154051671-47c4ffce-fa5f-4a69-bee3-02f09b1dbf3b.png)

Of course I could change the template, but this does not feel like a good solution. If someone else wants to run the source code of my app, he/she would have to to do all the changes to the css.template as I did, which is not very practical. 

Thus, is there an easy way to unset certain properties in runtime, so I can use it where I need it. Or, is it an option to fully remove all height properties from the template and let qt decide for the correct height? Most likely not, I guess you had a reason why you set the height property ;-).

Best
Daniel

**Comment by YeisonCardona** [comment]
Hi @dagginio 

That difference is so subtle that I never noticed.

That bug was introduced in the commit that adds the density scale feature, that's the reason for fixed height.
In the line: 
`height: {{36|density(density_scale)}}px;`
I miss the bottom border 
`height: {{36|density(density_scale, border=2)}}px;`
This will be fixed in the next commit and in the 2.9 release.

By the way,  there is a way to change styles in runtime, rewriting them:
`self.main.comboBox.style_sheet = "*{border-color: red; color: red}"`
or 
`self.main.comboBox.setStyleSheet("*{border-color: red; color: red}")`

Thanks for your report, I really appreciate it.
